### ISSUE TITLE
Extractor.exe not included in files

### ISSUE THREAD

**Issue by kimarudashi** [ramazanaktolu/AOWPackageExtractor#3]
Hello, the Extractor.exe mentioned in the README does not exist in the repo files. Can you either provide it or add a section in the README for generating the .exe file? Thank you!

**Comment by ramazanaktolu** [comment]
> Hello, the Extractor.exe mentioned in the README does not exist in the repo files. Can you either provide it or add a section in the README for generating the .exe file? Thank you!

Hi, exe file is in the releases section 
https://github.com/ramazanaktolu/AOWPackageExtractor/releases/tag/2.1
